/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Flathub API
 * OpenAPI spec version: 0.1.0
 */

export interface DeveloperSummary {
  total_apps: number
  total_installs: number
  verified_apps: number
  main_categories: string[]
  is_verified: boolean
}
