"""Add email account

Revision ID: 86061230b7bf
Revises: c8d39eb43e08
Create Date: 2025-10-05 11:07:27.796871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86061230b7bf'
down_revision = 'c8d39eb43e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['flathubuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailaccount_email'), 'emailaccount', ['email'], unique=True)
    op.create_index(op.f('ix_emailaccount_user'), 'emailaccount', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailaccount_user'), table_name='emailaccount')
    op.drop_index(op.f('ix_emailaccount_email'), table_name='emailaccount')
    op.drop_table('emailaccount')
    # ### end Alembic commands ###
