"""Add magic link login

Revision ID: c8d39eb43e08
Revises: b664044af9f3
Create Date: 2025-10-05 10:37:37.938334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d39eb43e08'
down_revision = 'b664044af9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magiclinktoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magiclinktoken_email'), 'magiclinktoken', ['email'], unique=False)
    op.create_index(op.f('ix_magiclinktoken_token'), 'magiclinktoken', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_magiclinktoken_token'), table_name='magiclinktoken')
    op.drop_index(op.f('ix_magiclinktoken_email'), table_name='magiclinktoken')
    op.drop_table('magiclinktoken')
    # ### end Alembic commands ###
